## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [45]:
import numpy as np
random_numbers = np.random.randint(0,11,5)
print(random_numbers)
for i in range(0,len(random_numbers)):
    if ((random_numbers[i]>3) & (random_numbers[i]<8)):
        random_numbers[i] = -abs(random_numbers[i])
print(random_numbers)

[4 3 5 8 1]
[-4  3 -5  8  1]


**2.** Заменить максимальный элемент случайного массива на 0

In [49]:
import numpy as np
random_numbers = np.random.randint(0,101,10)
print(random_numbers)
random_numbers [random_numbers == np.max(random_numbers)] = 0
print(random_numbers)

[80 24 98 82 98 58 88 32 33 64]
[80 24  0 82  0 58 88 32 33 64]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [66]:
import numpy as np
arr = np.array([np.random.randint(0,11,3),np.random.randint(0,11,3)]) 
print(arr)
result = list()
for i in range(0,len(arr[0])):
    result.append(arr[0][i]*arr[1])
print(result)

[[6 2 7]
 [8 3 2]]
[array([48, 18, 12]), array([16,  6,  4]), array([56, 21, 14])]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [93]:
import numpy as np
arr_A = np.random.randint(0, 11, size=(8, 3))
arr_B = np.random.randint(0, 11, size=(2, 2))
print(arr_A)
print(arr_B)
mask1 = np.isin(arr_A, arr_B[0])
mask2 = np.isin(arr_A, arr_B[1])
result = arr_A[np.logical_and(np.any(mask1, axis=1), np.any(mask2, axis=1))]
print(result)

[[ 2  9  4]
 [ 1  9 10]
 [ 5 10  3]
 [ 1 10 10]
 [ 2  3  8]
 [ 6  7  8]
 [ 9  3 10]
 [ 5  3  6]]
[[3 8]
 [5 5]]
[[ 5 10  3]
 [ 5  3  6]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [118]:
import numpy as np
arr_A = np.random.randint(0, 3, size=(10, 3))
print(arr_A)
result = list()
for i in range(arr_A.shape[0]):
    if ( not (np.all(arr_A[i]==arr_A[i][0]))):
        result.append(arr_A[i])
print(result)

[[0 1 1]
 [0 2 2]
 [1 0 2]
 [0 2 1]
 [1 1 1]
 [0 1 2]
 [0 0 1]
 [2 1 0]
 [2 1 1]
 [0 0 0]]
[array([0, 1, 1]), array([0, 2, 2]), array([1, 0, 2]), array([0, 2, 1]), array([0, 1, 2]), array([0, 0, 1]), array([2, 1, 0]), array([2, 1, 1])]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [123]:
import numpy as np
arr_A = np.random.randint(0, 2, size=(10, 2))
print(arr_A)
print(np.unique(arr_A,axis = 0))

[[1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]]
[[0 0]
 [0 1]
 [1 0]
 [1 1]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [145]:
import numpy as np
arr = np.random.randint(0, 11, size=(4, 3))
print(arr)          
# numpy
diag = np.diag(arr)
print(np.prod(diag[diag!=0]))
# python only
product = 1
for i in range(min(len(arr), len(arr[0]))):
    if arr[i][i] != 0:
         product *= arr[i][i]
print(product)

[[5 5 9]
 [7 3 8]
 [9 2 6]
 [9 1 8]]
90
90


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [156]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
# numpy
print(np.array_equal(np.sort(x), np.sort(y)))
# python only
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
sorted_x = sorted(x)
sorted_y = sorted(y)
result = True
if len(sorted_y) != len(sorted_x):
       result = False
for i in range(len(sorted_x)):
    if sorted_x[i] != sorted_y[i]:
        result = False
print(result)

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [172]:
# numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0, 9])
mask = np.hstack(([False], x[:-1] == 0))
max_elem = np.max(x[mask])
print(max_elem)
# python only
x = [6, 2, 0, 3, 0, 0, 5, 7, 0, 9]
max_elem = None
for i in range(1, len(x)):
    if x[i-1] == 0 and (max_elem is None or x[i] > max_elem):
        max_elem = x[i]
print(max_elem)

9
9


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [191]:
# numpy
x = np.array([2, 2, 2, 3, 3, 3, 5])
vals, counts = np.unique(x, return_counts=True)
print(vals, counts)
# python only
x = [2, 2, 2, 3, 3, 3, 5]
vals = []
counts = []
for val in x:
        if val not in vals:
            vals.append(val)
            counts.append(1)
        else:
            idx = vals.index(val)
            counts[idx] += 1
print(vals, counts)

[2 3 5] [3 3 1]
[2, 3, 5] [3, 3, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [202]:
# numpy
X = np.random.randint(0,11,size = (3,4))
Y = np.random.randint(0,11,size = (3,4))
def euclidean_distance_matrix(X, Y):
    X_norm = (X ** 2).sum(axis=1, keepdims=True)
    Y_norm = (Y ** 2).sum(axis=1, keepdims=True)
    distances = np.sqrt(X_norm + Y_norm.T - 2 * np.dot(X, Y.T))
    return distances
print(euclidean_distance_matrix(X, Y))
# python only
from scipy.spatial.distance import cdist
print(cdist(X, Y))
%timeit euclidean_distance_matrix(X, Y)
%timeit cdist(X, Y)

[[12.84523258  6.4807407  11.09053651]
 [ 4.69041576  6.55743852  6.78232998]
 [ 8.71779789  9.43398113  7.07106781]]
[[12.84523258  6.4807407  11.09053651]
 [ 4.69041576  6.55743852  6.78232998]
 [ 8.71779789  9.43398113  7.07106781]]
43.6 µs ± 7.59 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
12.9 µs ± 821 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [205]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [208]:
average_calories = np.mean(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [207]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [210]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [211]:
percentiles = np.arange(1, 101)
for p in percentiles:
    nth_percentile = np.percentile(calorie_stats, p)
    if nth_percentile > 60:
        break
print(nth_percentile)

70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [214]:
more_calories = np.mean(calorie_stats > 60) * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [215]:
calorie_std = np.std(calorie_stats)
print(calorie_std)
# Можно использовать это значение чтобы понять насколько данные отличаются друг
# от друга

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [218]:
Мы можем пострить маркетиноговую компанию вокруг того факта что CrunchieMunchies 
обладают одной из самых низких колорийностей на рынке, обходя по этому 
показателю более 90 процентов конкурентов.

SyntaxError: invalid syntax (3312548873.py, line 2)